apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress-container
        image: busybox
        command: ["sh", "-c", "while :; do :; done"]
